# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run: npm run build

      - run: npm run test

      - run: curl -u admin:AKCp5buTmXMWkbWA7gDihmqntxMuaGFWWT1oF5mZHwjvRb6SUck1aQxQD1gGmyvNwAWoyT8nr http://rnakkiran.jfrog.io/rnakkiran/api/npm/auth > ~/.npmrc

      - run: npm config set registry https://rnakkiran.jfrog.io/rnakkiran/api/npm/npm/

      - run: mkdir -p  ~/repo/release/upper

      - run: cp -r ~/repo/build/src/*       ~/repo/release/upper/

      - run: cp ~/repo/package.json        ~/repo/release/upper/

      - run: cp ~/repo/package-lock.json   ~/repo/release/upper/

      - run: cp ~/repo/README.md          ~/repo/release/upper/

      - run: cd ~/repo/release/upper && npm publish --access public --registry https://rnakkiran.jfrog.io/rnakkiran/api/npm/npm/

      - run: ls -l ~/repo/release/upper







